"""added description and href

Revision ID: a10f260217bc
Revises: cd1dff556202
Create Date: 2020-05-25 14:35:54.810357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10f260217bc'
down_revision = 'cd1dff556202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seals', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('seals', sa.Column('playlist_href', sa.String(length=128), nullable=True))
    op.drop_column('seals', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seals', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('seals', 'playlist_href')
    op.drop_column('seals', 'description')
    # ### end Alembic commands ###
